### ISSUE TITLE
add readme describing what the plugin does

### ISSUE THREAD

**Issue by stuartlamour** [pauln/moodle-atto_filedragdrop#1]
This Moodle plugin for atto lets you drag any file into atto - from docs to videos - and have them upload and create a link to the file, with the file title, which you can then edit in atto.

If you are using Moodle media filters any multimedia files will display inline via the filter once published.

Installation instructions :

**Comment by pauln** [comment]
Thanks for prompting me to finish tidying this up, Stuart.  I've added a README (and a LICENSE), tidied up the version info and submitted it to the Moodle plugin database for approval.
